import { User, Task, UserRole, TaskStatus, TaskPriority, RecurrenceFrequency, Message, UserStatus } from './types';

export const USERS: User[] = [
  { id: 'user-1', name: 'Admin', email: 'evelyn.reed@example.com', role: UserRole.Admin, status: UserStatus.Active, avatar: 'https://i.pravatar.cc/150?u=user-1', password: 'admin', forcePasswordChange: false, theme: 'light', lastLogin: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString() },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-1',
    title: 'Conduct weekly inventory of narcotics',
    checklist: [
      { id: 't1c1', text: 'Perform a full count of all controlled substances in the safe.', isCompleted: false },
      { id: 't1c2', text: 'Log the results in the inventory binder.', isCompleted: false },
    ],
    assigneeIds: [],
    deadline: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: TaskStatus.ToDo,
    isPrivate: false,
    priority: TaskPriority.Important,
    isRecurring: true,
    recurrenceFrequency: RecurrenceFrequency.Weekly,
    recurrenceEndDate: null,
    isArchived: false,
    createdBy: 'user-1',
    comments: [],
  },
  {
    id: 'task-2',
    title: 'Process prescription refills from online portal',
    checklist: [
      { id: 't2c1', text: 'Review all pending refill requests from the patient portal.', isCompleted: false },
      { id: 't2c2', text: 'Prepare all pending refill requests for pharmacist verification.', isCompleted: false },
    ],
    assigneeIds: [],
    deadline: new Date().toISOString(),
    status: TaskStatus.ToDo,
    isPrivate: false,
    priority: TaskPriority.Urgent,
    isRecurring: false,
    recurrenceFrequency: null,
    recurrenceEndDate: null,
    isArchived: false,
    createdBy: 'user-1',
    comments: [],
  },
  {
    id: 'task-3',
    title: 'Restock shelves in Aisle 3',
    checklist: [
      { id: 't3c1', text: 'Replenish all over-the-counter medications in Aisle 3.', isCompleted: false },
      { id: 't3c2', text: 'Replenish all front-end supplies in Aisle 3.', isCompleted: false },
    ],
    assigneeIds: [],
    deadline: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    status: TaskStatus.ToDo,
    isPrivate: false,
    priority: TaskPriority.General,
    isRecurring: false,
    recurrenceFrequency: null,
    recurrenceEndDate: null,
    isArchived: false,
    createdBy: 'user-1',
    comments: [],
  },
  {
    id: 'task-4',
    title: 'Clean and sanitize dispensing counters',
    checklist: [
      { id: 't4c1', text: 'Thoroughly clean all surfaces in the dispensing area.', isCompleted: true },
      { id: 't4c2', text: 'Clean all tools and equipment (spatulas, counting trays).', isCompleted: true },
      { id: 't4c3', text: 'Sanitize all equipment after cleaning.', isCompleted: true },
    ],
    assigneeIds: [],
    deadline: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    status: TaskStatus.Done,
    isPrivate: false,
    priority: TaskPriority.General,
    isRecurring: false,
    recurrenceFrequency: null,
    recurrenceEndDate: null,
    isArchived: false,
    createdBy: 'user-1',
    comments: [],
    completedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
   {
    id: 'task-5',
    title: 'Follow up on insurance claim rejections',
    checklist: [
      { id: 't5c1', text: 'Contact insurance providers for the list of rejected claims.', isCompleted: false },
      { id: 't5c2', text: 'Resubmit claims with necessary corrections.', isCompleted: false },
    ],
    assigneeIds: [],
    deadline: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    status: TaskStatus.ToDo,
    isPrivate: false,
    priority: TaskPriority.Important,
    isRecurring: false,
    recurrenceFrequency: null,
    recurrenceEndDate: null,
    isArchived: false,
    createdBy: 'user-1',
    comments: [],
  },
];

export const INITIAL_MESSAGES: Message[] = [];